name: flutter_application_1
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Icon bawaan iOS
  cupertino_icons: ^1.0.8

  # Firebase packages
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9

  # Grafik (Pie chart dll)
  fl_chart: ^0.64.0

  # Format tanggal dan mata uang
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
